# Generated by Django 6.0.3 on 2026-03-05 13:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tuition_amount', models.DecimalField(decimal_places=2, help_text='50% - Fixed costs (tuition)', max_digits=15)),
                ('upkeep_amount', models.DecimalField(decimal_places=2, help_text='30% - Variable costs (rent, food, utilities)', max_digits=15)),
                ('investment_amount', models.DecimalField(decimal_places=2, help_text='20% - Capital to invest', max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allocation Plan',
                'verbose_name_plural': 'Allocation Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_type', models.CharField(choices=[('MMF', 'Money Market Fund'), ('CONSOLIDATED', 'Premier Consolidated Holdings (Simulated)')], default='MMF', max_length=20)),
                ('fund_name', models.CharField(help_text='Name of the fund', max_length=255)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current NAV including accrued interest', max_digits=15)),
                ('annual_yield_percentage', models.DecimalField(decimal_places=3, default=Decimal('5.0'), help_text='Annual Effective Yield (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('accumulated_interest', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LIQUIDATED', 'Liquidated'), ('MATURED', 'Matured')], default='ACTIVE', max_length=20)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('last_interest_accrual', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='investments.allocationplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Position',
                'verbose_name_plural': 'Investment Positions',
                'ordering': ['-investment_date'],
            },
        ),
        migrations.CreateModel(
            name='InterestAccrualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_accrued', models.DecimalField(decimal_places=4, max_digits=15)),
                ('value_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('value_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accrual_date', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accrual_logs', to='investments.investmentposition')),
            ],
            options={
                'verbose_name': 'Interest Accrual Log',
                'verbose_name_plural': 'Interest Accrual Logs',
                'ordering': ['-accrual_date'],
            },
        ),
        migrations.AddIndex(
            model_name='investmentposition',
            index=models.Index(fields=['student', 'status'], name='investments_student_2d508d_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentposition',
            index=models.Index(fields=['status', 'last_interest_accrual'], name='investments_status_114973_idx'),
        ),
        migrations.AddIndex(
            model_name='interestaccruallog',
            index=models.Index(fields=['position', 'accrual_date'], name='investments_positio_51d15c_idx'),
        ),
    ]
