# Generated by Django 6.0.3 on 2026-03-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='Whether user has completed initial onboarding setup'),
        ),
    ]
