# Generated by Django 6.0.3 on 2026-03-05 13:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HELBAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helb_reference_number', models.CharField(blank=True, help_text='HELB unique account reference', max_length=50, null=True, unique=True)),
                ('total_approved_amount', models.DecimalField(decimal_places=2, help_text='Total approved HELB loan amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('course_duration_years', models.PositiveIntegerField(default=4, help_text='Expected course duration in years')),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helb_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HELB Account',
                'verbose_name_plural': 'HELB Accounts',
            },
        ),
        migrations.CreateModel(
            name='DisbursementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_frequency', models.CharField(choices=[('SEMESTER', 'Per Semester'), ('QUARTERLY', 'Per Quarter'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='SEMESTER', max_length=20)),
                ('schedule_json', models.JSONField(default=dict, help_text='Projected schedule: {year: {semester: amount, ...}, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helb_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_schedule', to='helb.helbaccount')),
            ],
            options={
                'verbose_name': 'Disbursement Schedule',
                'verbose_name_plural': 'Disbursement Schedules',
            },
        ),
        migrations.CreateModel(
            name='DisbursementProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projected_date', models.DateField(help_text='When this projection was made')),
                ('next_disbursement_date', models.DateField(help_text='Projected next disbursement')),
                ('projected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High (95%+)'), ('MEDIUM', 'Medium (70-95%)'), ('LOW', 'Low (<70%)')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helb_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='helb.helbaccount')),
            ],
            options={
                'verbose_name': 'Disbursement Projection',
                'verbose_name_plural': 'Disbursement Projections',
                'ordering': ['-projected_date'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expected_date', models.DateField(help_text='Expected disbursement date')),
                ('disbursal_date', models.DateField(blank=True, help_text='Actual disbursement date', null=True)),
                ('received_date', models.DateField(blank=True, help_text='Date received in M-Pesa', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helb_disbursements', to=settings.AUTH_USER_MODEL)),
                ('helb_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='helb.helbaccount')),
            ],
            options={
                'verbose_name': 'Disbursement',
                'verbose_name_plural': 'Disbursements',
                'ordering': ['-expected_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='helb_disbur_student_69ad5c_idx'), models.Index(fields=['expected_date'], name='helb_disbur_expecte_e54d1e_idx')],
            },
        ),
    ]
