# Generated by Django 6.0.3 on 2026-03-27 11:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='allocation_20',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='allocation_30',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='allocation_50',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='accommodation_limit',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Monthly accommodation limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='education_limit',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Monthly education limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='entertainment_limit',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Monthly entertainment limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='food_limit',
            field=models.DecimalField(decimal_places=2, default=8000, help_text='Monthly food limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='healthcare_limit',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Monthly healthcare limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_limit',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='Monthly other limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='transport_limit',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='Monthly transport limit', max_digits=15),
        ),
        migrations.AddField(
            model_name='budget',
            name='utilities_limit',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Monthly utilities limit', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('EXPENSE', 'Expense')], max_length=20),
        ),
        migrations.CreateModel(
            name='B2CTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('purpose', models.CharField(choices=[('SalaryPayment', 'Salary Payment'), ('BusinessPayment', 'Business Payment'), ('PromotionalPayment', 'Promotional Payment')], default='BusinessPayment', max_length=50)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_description', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'B2C Transaction',
                'verbose_name_plural': 'B2C Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_amount', models.DecimalField(decimal_places=2, help_text='Daily budget limit to send to phone', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10'))])),
                ('phone_number', models.CharField(help_text='Phone number to send daily limit (254XXXXXXXXX format)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable automatic daily disbursement')),
                ('disbursement_time', models.TimeField(default='06:00:00', help_text='Time to send daily amount (HH:MM:SS format, in EAT)')),
                ('remaining_today', models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount for today', max_digits=10)),
                ('last_disbursement_date', models.DateField(blank=True, help_text='Date of last daily disbursement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Limit',
                'verbose_name_plural': 'Daily Limits',
            },
        ),
        migrations.CreateModel(
            name='DailyDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount sent', max_digits=10)),
                ('phone_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('disbursement_date', models.DateField(auto_now_add=True, help_text='Date of disbursement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('b2c_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_disbursement', to='finance.b2ctransaction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_disbursements', to=settings.AUTH_USER_MODEL)),
                ('daily_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='finance.dailylimit')),
            ],
            options={
                'verbose_name': 'Daily Disbursement',
                'verbose_name_plural': 'Daily Disbursements',
                'ordering': ['-disbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number that sent money', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('mpesa_code', models.CharField(help_text='M-Pesa transaction code (e.g., LILNDLC42)', max_length=50, unique=True)),
                ('phone_number_initiator', models.CharField(help_text='Initiating phone number', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(help_text='Daraja C2B transaction ID from M-Pesa', max_length=100, unique=True)),
                ('reference', models.CharField(help_text='Reference/description', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='b2ctransaction',
            index=models.Index(fields=['status', '-created_at'], name='finance_b2c_status_632755_idx'),
        ),
        migrations.AddIndex(
            model_name='b2ctransaction',
            index=models.Index(fields=['student', '-created_at'], name='finance_b2c_student_85d2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydisbursement',
            index=models.Index(fields=['student', '-disbursement_date'], name='finance_dai_student_4061a1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailydisbursement',
            index=models.Index(fields=['status', '-disbursement_date'], name='finance_dai_status_99077a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailydisbursement',
            unique_together={('student', 'disbursement_date')},
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', '-created_at'], name='finance_mpe_status_772dca_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['student', '-created_at'], name='finance_mpe_student_cf8a87_idx'),
        ),
    ]
