# Generated by Django 6.0.3 on 2026-03-27 17:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_budget_allocation_20_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('HELB', 'HELB Loan'), ('SALARY', 'Salary/Employment'), ('SCHOLARSHIP', 'Scholarship'), ('PARENTS', 'Parents/Family'), ('SAVINGS', 'Personal Savings'), ('PART_TIME', 'Part-time Work'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received from this source', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEMESTER', 'Per Semester'), ('ANNUAL', 'Annual')], default='ONE_TIME', help_text='How often the student receives this income', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about this income source', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Source',
                'verbose_name_plural': 'Fund Sources',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'source_type')},
            },
        ),
    ]
