# Generated by Django 6.0.3 on 2026-04-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fundsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category_due_dates',
            field=models.JSONField(blank=True, default=dict, help_text="Expected disbursement dates per category, e.g. {'Rent': '2026-05-01'}"),
        ),
    ]
